openapi: "3.0.0"
info:
  title: Simple Blog
  version: "1.2"
tags:
  - name: Users
  - name: Posts
  - name: Media

paths:
  /users:
    post:
      tags:
        - Users
      description: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "201":
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenDto"
        "400":
          description: Bad request body
        "403":
          description: Registration is disabled
        "500":
          description: Internal server error
  /users/token:
    post:
      tags:
        - Users
      description: Generate a user token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        "200":
          description: Token created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenDto"
        "400":
          description: Bad request body
        "500":
          description: Internal server error
  /posts/published:
    get:
      tags:
        - Posts
      description: Get published posts
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number
          required: false
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagePostDto"
        "500":
          description: Internal server error
  /posts/published/{id}:
    get:
      tags:
        - Posts
      description: Get a published post by id
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Post id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostDto"
        "404":
          description: Post not found
        "500":
          description: Internal server error
  /rss/posts:
    get:
      tags:
        - Posts
      description: Get an RSS feed with published posts
      responses:
        "200":
          description: OK
          content:
            application/rss+xml:
              schema:
                type: string
        "500":
          description: Internal server error
  /posts/editor:
    get:
      tags:
        - Posts
      description: Get all posts, both published and drafts
      security:
        - bearerAuth: [ ]
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number
          required: false
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PagePostDto"
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
    post:
      tags:
        - Posts
      description: Create a new post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostEditorDto"
      security:
        - bearerAuth: [ ]
      responses:
        "201":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostDto"
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
  /posts/editor/{id}:
    get:
      tags:
        - Posts
      security:
        - bearerAuth: [ ]
      description: Get a post, whether it's published or not
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Post id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostDto"
        "401":
          description: Unauthorized
        "404":
          description: Post not found
        "500":
          description: Internal server error
    put:
      tags:
        - Posts
      security:
        - bearerAuth: [ ]
      description: Update an existing post
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Post id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostEditorDto"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostDto"
        "401":
          description: Unauthorized
        "404":
          description: Post not found
        "500":
          description: Internal server error
    delete:
      tags:
        - Posts
      security:
        - bearerAuth: [ ]
      description: Delete an existing post
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Post id
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "404":
          description: Post not found
        "500":
          description: Internal server error
  /media:
    get:
      tags:
        - Media
      description: Get all media files
      security:
        - bearerAuth: [ ]
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Page number
          required: false
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PageMediaDto"
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
    post:
      tags:
        - Media
      security:
        - bearerAuth: [ ]
      description: Upload a file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                properties:
                  id:
                    type: string
                    description: Id of the media file
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
  /media/{id}:
    get:
      tags:
        - Media
      description: Get a media file
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Media file id
      responses:
        "200":
          description: File content
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "404":
          description: Media file not found
        "500":
          description: Internal server error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    TokenDto:
      type: object
      properties:
        token:
          type: string
        expires:
          type: integer
          format: int64
      required:
        - token
        - expires
    PostPreviewDto:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        summary:
          type: string
        date:
          type: string
          format: date-time
        visible:
          type: boolean
      required:
        - id
        - title
        - summary
        - date
        - visible
    PostDto:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        summary:
          type: string
        text:
          type: string
        date:
          type: string
          format: date-time
        visible:
          type: boolean
      required:
        - id
        - title
        - summary
        - text
        - date
        - visible
    PostEditorDto:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        summary:
          type: string
        text:
          type: string
        date:
          type: string
          format: date-time
        visible:
          type: boolean
      required:
        - title
        - summary
        - text
        - visible
    ErrorDto:
      required:
        - message
        - messageDefinition
      properties:
        message:
          type: string
          description: Error message
          example: User already exists
        messageDefinition:
          type: string
          description: Error message definition
          example: USER_ALREADY_EXISTS
    PageDto:
      required:
        - page
        - totalPages
        - items
      properties:
        page:
          type: integer
          description: Current page
        totalPages:
          type: integer
          description: Total pages
        items:
          type: array
          items: { }
          description: Page items
    PagePostDto:
      allOf:
        - $ref: '#/components/schemas/PageDto'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/PostPreviewDto'
    MediaDto:
      type: object
      properties:
        id:
          type: string
        originalFilename:
          type: string
        contentType:
          type: string
        date:
          type: string
          format: date-time
      required:
        - id
        - originalFilename
        - contentType
        - date
    PageMediaDto:
      allOf:
        - $ref: '#/components/schemas/PageDto'
        - type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/MediaDto'
