services:
  simple-blog-backend:
    image: mcr.microsoft.com/devcontainers/java:21
    network_mode: host
    env_file:
      - .env
    command: ["sleep", "infinity"]
    volumes:
      - ../..:/workspaces:cached
